common:
  data_path: "../data/reviews.csv"
  train_test_ratio: 0.8
  max_words: 25000
  max_len: 200
  limit_records: 5000


model:
  type: "LSTM"  # or "RNN"
  model_path: "../models/generic_model"
  epochs: 5
  batch_size: 64

spark:
  config:
    appName: "Sentiment Analysis"
    master: "local"
    executor_memory: "8g"
    driver_memory: "8g"
    num_executors: 2
    executor_cores: 2
    pyspark_enable: true
    stopwords_path: "../resources/stopwords.txt"
  ml0lib:
    model_path: "../models/sparkml_model"


gan:
  synthetic_data_rows: 1000
